namespace Forge.Core.Models;

public record ShipmentDetailResponseModel(
    int Id,
    string ShipmentNumber,
    int SalesOrderId,
    string SalesOrderNumber,
    string CustomerName,
    int? ShippingAddressId,
    string Status,
    string? Carrier,
    int? CarrierId,
    string? TrackingNumber,
    string? ScanCode,
    DateTimeOffset? ShippedDate,
    DateTimeOffset? DeliveredDate,
    decimal? ShippingCost,
    decimal? Weight,
    string? Notes,
    string? PickupConfirmationNumber,
    DateTimeOffset? PickupScheduledDate,
    int? InvoiceId,
    List<ShipmentLineResponseModel> Lines,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);
