namespace Forge.Core.Entities;

/// <summary>
/// Tenant-level override for a single UI i18n label (one row per key + language).
/// Overrides are merged over the shipped i18n JSON catalogs at load time so an
/// install can rename labels (e.g. "Customer" → "Client") without a rebuild.
/// Revert-to-default is a soft delete of the row.
/// </summary>
public class I18nLabelOverride : BaseAuditableEntity
{
    /// <summary>Dotted i18n key exactly as it appears in the shipped catalogs (e.g. "customers.fields.name").</summary>
    public string Key { get; set; } = string.Empty;

    /// <summary>ISO language code the override applies to (e.g. "en", "es").</summary>
    public string LanguageCode { get; set; } = string.Empty;

    /// <summary>The override text shown instead of the shipped value.</summary>
    public string Value { get; set; } = string.Empty;

    /// <summary>True when this row was generated by machine translation (fan-out from a human edit in another language).</summary>
    public bool IsMachineTranslated { get; set; }

    /// <summary>
    /// True when a machine translation could not be produced yet (translation service unreachable).
    /// Pending rows hold the source-language text as a placeholder and are excluded from the
    /// active merge map until translated (by the retry job or a manual retry).
    /// </summary>
    public bool IsPendingTranslation { get; set; }

    /// <summary>For machine-translated rows: the language of the human override this row was derived from.</summary>
    public string? SourceLanguageCode { get; set; }
}
