using FluentAssertions;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;

using Npgsql;

using Forge.Api.Services;
using Forge.Core.Models;
using Forge.Tests.Helpers;

namespace Forge.Tests.Services;

/// <summary>
/// Round-trip coverage of the admin dump → clean-rebuild import against real Postgres. Uses two
/// uniquely-named scratch databases on the collection's server (never the shared fixture DB — the
/// import TRUNCATEs, which would nuke collection state) with a small hand-made schema: the service
/// is schema-agnostic, so the full forge schema adds nothing but minutes here.
/// </summary>
[Collection(PostgresCollection.Name)]
public sealed class DatabaseTransferServiceTests(PostgresFixture fixture) : IAsyncLifetime
{
    private readonly string _stamp = DateTime.UtcNow.Ticks.ToString();
    private string SourceDb => $"forge_transfer_src_{_stamp}";
    private string TargetDb => $"forge_transfer_dst_{_stamp}";

    private const string Schema = """
        CREATE TABLE parents (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            deleted_at timestamptz
        );
        CREATE TABLE children (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parent_id bigint NOT NULL REFERENCES parents(id),
            note text
        );
        CREATE TABLE junk_log (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payload text
        );
        """;

    public async Task InitializeAsync()
    {
        await ExecAsync(AdminConn(), $"CREATE DATABASE \"{SourceDb}\"");
        await ExecAsync(AdminConn(), $"CREATE DATABASE \"{TargetDb}\"");
        await ExecAsync(Conn(SourceDb), Schema);
        await ExecAsync(Conn(TargetDb), Schema);
    }

    public async Task DisposeAsync()
    {
        await ExecAsync(AdminConn(), $"DROP DATABASE IF EXISTS \"{SourceDb}\" WITH (FORCE)");
        await ExecAsync(AdminConn(), $"DROP DATABASE IF EXISTS \"{TargetDb}\" WITH (FORCE)");
    }

    [Fact]
    public async Task DumpThenImport_RoundTrips_Excludes_PurgesSoftDeleted_FixesSequences_AndFlagsOrphans()
    {
        await ExecAsync(Conn(SourceDb), """
            INSERT INTO parents (name, deleted_at) VALUES ('keep', NULL), ('tombstone', now());
            INSERT INTO children (parent_id, note) VALUES (1, 'of keep');
            INSERT INTO junk_log (payload) VALUES ('noise-1'), ('noise-2');
            """);

        // ── dump from source ─────────────────────────────────────────────────────────────────────
        var sourceService = ServiceFor(SourceDb);
        using var zip = new MemoryStream();
        await sourceService.WriteDumpZipAsync(zip);
        zip.Length.Should().BeGreaterThan(0);

        var summary = await sourceService.GetSummaryAsync();
        summary.Tables.Should().HaveCount(3);

        // ── import into target: junk excluded, tombstones purged ────────────────────────────────
        var targetService = ServiceFor(TargetDb);
        zip.Position = 0;
        var report = await targetService.ImportZipAsync(
            zip, new DatabaseImportOptionsModel(["junk_*"], PurgeSoftDeleted: true, AllowFkOrphans: false));

        report.Success.Should().BeTrue();
        report.Loaded.Should().HaveCount(2);
        report.Excluded.Should().Equal("public.junk_log");
        report.SoftDeletedPurged.Should().Be(1);
        report.FkOrphans.Should().BeEmpty(); // the tombstone had no children

        (await ScalarAsync(Conn(TargetDb), "SELECT count(*) FROM parents")).Should().Be(1);
        (await ScalarAsync(Conn(TargetDb), "SELECT count(*) FROM junk_log")).Should().Be(0);

        // Sequences continue past the imported ids — a new insert must not collide.
        await ExecAsync(Conn(TargetDb), "INSERT INTO parents (name) VALUES ('after-import')");
        (await ScalarAsync(Conn(TargetDb), "SELECT count(*) FROM parents")).Should().Be(2);

        // ── orphan detection: excluding the parent table strands the dumped child whose parent
        // is not in the target (parent 1 IS still there from the import above, so re-importing
        // children alone leaves zero orphans; drop parent 1's row first to force one) ────────────
        await ExecAsync(Conn(TargetDb), "DELETE FROM children; DELETE FROM parents");
        zip.Position = 0;
        var orphaned = await targetService.ImportZipAsync(
            zip, new DatabaseImportOptionsModel(["parents", "junk_*"], PurgeSoftDeleted: false, AllowFkOrphans: false));

        orphaned.Success.Should().BeFalse();
        var violation = orphaned.FkOrphans.Should().ContainSingle().Subject;
        violation.ChildTable.Should().Be("public.children");
        violation.ParentTable.Should().Be("public.parents");
        violation.Rows.Should().Be(1);
    }

    // ── plumbing ─────────────────────────────────────────────────────────────────────────────────

    private DatabaseTransferService ServiceFor(string db)
    {
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ConnectionStrings:DefaultConnection"] = Conn(db),
            })
            .Build();
        return new DatabaseTransferService(config, NullLogger<DatabaseTransferService>.Instance);
    }

    private string Conn(string db) =>
        new NpgsqlConnectionStringBuilder(fixture.ConnectionString) { Database = db }.ConnectionString;

    private string AdminConn() =>
        new NpgsqlConnectionStringBuilder(fixture.ConnectionString) { Database = "postgres" }.ConnectionString;

    private static async Task ExecAsync(string connString, string sql)
    {
        await using var conn = new NpgsqlConnection(connString);
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand(sql, conn);
        await cmd.ExecuteNonQueryAsync();
    }

    private static async Task<long> ScalarAsync(string connString, string sql)
    {
        await using var conn = new NpgsqlConnection(connString);
        await conn.OpenAsync();
        await using var cmd = new NpgsqlCommand(sql, conn);
        return (long)(await cmd.ExecuteScalarAsync())!;
    }
}
